dbHost: localhost
dbPort: 5432
dbName: app_security
dbUsername: admin
dbPassword: super_secret_password
dbSchema: app_security

spring:
  application:
    name: security-service
    version: 0.0.1.test
    description: security service
  datasource:
    url: jdbc:postgresql://localhost:5432/app_security
    username: admin
    password: super_secret_password
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: ${dbSchema}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${dbSchema}
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
  server:
    port: 9090

info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}
    description: ${spring.application.description}

springdoc:
  swagger-ui:
    path: /
